import type { MediaItem } from "./types";

export const sampleMedia: MediaItem[] = [
  {
    id: "satun-flood-01",
    title: "เฝ้าระวังน้ำท่วมฉับพลัน อำเภอควนโดน",
    description:
      "อินโฟกราฟิกจุดเสี่ยง วิธีติดตามประกาศ และรายการสิ่งของจำเป็นสำหรับครัวเรือนในพื้นที่เฝ้าระวัง",
    phase: "before",
    category: "น้ำท่วม",
    eventDate: "2026-07-28",
    location: "อำเภอควนโดน",
    keywords: ["น้ำท่วม", "ฝนตกหนัก", "เตรียมพร้อม"],
    altText: "อินโฟกราฟิกเตรียมพร้อมรับมือน้ำท่วมฉับพลัน",
    fileName: "เตรียมพร้อม-น้ำท่วม-ควนโดน.jpg",
    fileType: "image/jpeg",
    status: "published",
    createdAt: "2026-07-28T08:30:00.000Z",
  },
  {
    id: "satun-dengue-02",
    title: "หยุดยุงลาย ป้องกันไข้เลือดออกในชุมชน",
    description:
      "สื่อประชาสัมพันธ์มาตรการ 3 เก็บ ป้องกัน 3 โรค สำหรับ อสม. โรงเรียน และประชาชนทั่วไป",
    phase: "before",
    category: "โรคติดต่อ",
    eventDate: "2026-07-23",
    location: "ทุกอำเภอในจังหวัดสตูล",
    keywords: ["ไข้เลือดออก", "ยุงลาย", "3 เก็บ"],
    altText: "โปสเตอร์รณรงค์กำจัดแหล่งเพาะพันธุ์ยุงลาย",
    fileName: "หยุดยุงลาย-3เก็บ.png",
    fileType: "image/png",
    status: "published",
    createdAt: "2026-07-23T03:15:00.000Z",
  },
  {
    id: "satun-flood-live-03",
    title: "แนวทางปฏิบัติระหว่างเกิดอุทกภัย",
    description:
      "ข้อควรทำทันทีเมื่อระดับน้ำเพิ่มสูง การดูแลยาและอาหาร และช่องทางแจ้งเหตุฉุกเฉินในจังหวัดสตูล",
    phase: "during",
    category: "น้ำท่วม",
    eventDate: "2026-07-20",
    location: "พื้นที่ประสบอุทกภัย",
    keywords: ["อุทกภัย", "ฉุกเฉิน", "ความปลอดภัย"],
    altText: "คู่มือปฏิบัติตัวอย่างปลอดภัยระหว่างเกิดอุทกภัย",
    fileName: "ระหว่างน้ำท่วม-ปลอดภัย.jpg",
    fileType: "image/jpeg",
    status: "published",
    createdAt: "2026-07-20T10:05:00.000Z",
  },
  {
    id: "satun-haze-04",
    title: "ค่าฝุ่นสูง ดูแลปอดอย่างไร",
    description:
      "คำแนะนำสำหรับเด็ก ผู้สูงอายุ หญิงตั้งครรภ์ และผู้มีโรคประจำตัวในช่วงมีหมอกควัน",
    phase: "during",
    category: "หมอกควัน",
    eventDate: "2026-07-14",
    location: "จังหวัดสตูล",
    keywords: ["PM2.5", "หมอกควัน", "กลุ่มเสี่ยง"],
    altText: "อินโฟกราฟิกการดูแลสุขภาพเมื่อค่าฝุ่นสูง",
    fileName: "ดูแลปอด-PM25.png",
    fileType: "image/png",
    status: "published",
    createdAt: "2026-07-14T06:45:00.000Z",
  },
  {
    id: "satun-recovery-05",
    title: "ทำความสะอาดบ้านหลังน้ำลด ลดโรค ลดเชื้อรา",
    description:
      "ขั้นตอนกลับเข้าบ้านอย่างปลอดภัย การฆ่าเชื้อพื้นผิว และการคัดแยกอาหารที่ปนเปื้อน",
    phase: "after",
    category: "ฟื้นฟูหลังเหตุ",
    eventDate: "2026-07-08",
    location: "พื้นที่หลังน้ำลด",
    keywords: ["น้ำลด", "ทำความสะอาด", "เชื้อรา"],
    altText: "คู่มือทำความสะอาดบ้านหลังน้ำลด",
    fileName: "หลังน้ำลด-ทำความสะอาด.jpg",
    fileType: "image/jpeg",
    status: "published",
    createdAt: "2026-07-08T02:20:00.000Z",
  },
  {
    id: "satun-road-06",
    title: "ถอดบทเรียนอุบัติเหตุทางถนนช่วงเทศกาล",
    description:
      "สรุปปัจจัยเสี่ยงและแนวทางสื่อสารเพื่อป้องกันการเกิดเหตุซ้ำในระดับครอบครัวและชุมชน",
    phase: "after",
    category: "อุบัติเหตุ",
    eventDate: "2026-06-30",
    location: "จังหวัดสตูล",
    keywords: ["อุบัติเหตุ", "ถอดบทเรียน", "ป้องกัน"],
    altText: "สรุปบทเรียนอุบัติเหตุทางถนนเพื่อป้องกันเหตุซ้ำ",
    fileName: "ถอดบทเรียน-ถนน.pdf",
    fileType: "application/pdf",
    status: "published",
    createdAt: "2026-06-30T04:00:00.000Z",
  },
];
